// ============================================================
// YojanaFind — schemes-data.js
// Complete offline database of 18 Indian Government Schemes
// ============================================================

const LOCAL_SCHEMES = [
  {
    id: 1,
    name: "PM Scholarship Scheme (PMSS)",
    name_hi: "पीएम छात्रवृत्ति योजना",
    ministry: "Kendriya Sainik Board · Ministry of Defence",
    icon: "🎓",
    icon_bg: "blue",
    description: "Scholarship for wards of ex-servicemen and coast guard personnel for technical and professional degree courses at undergraduate level. Merit-based with 60% in Class 12.",
    description_hi: "भूतपूर्व सैनिकों और तटरक्षक कर्मियों के वार्डों के लिए तकनीकी और व्यावसायिक स्नातक डिग्री कोर्स के लिए छात्रवृत्ति।",
    benefit: "₹2,000 – ₹3,000 per month",
    benefit_hi: "₹2,000 – ₹3,000 प्रति माह",
    category: "education",
    minAge: 18, maxAge: 25, maxIncome: 3,
    categories: ["general","obc","sc","st","ews"],
    genders: ["male","female","other"],
    situations: ["student"],
    tags: ["Education","Student","18-25","Central"],
    apply_url: "https://ksb.gov.in/pm-scholarship.htm",
    official_url: "https://ksb.gov.in",
    badge: null,
    steps: [
      { title: "Check Eligibility", detail: "Verify 60%+ marks in 12th and ex-serviceman ward status. Wards of current serving personnel are not eligible." },
      { title: "Register on Portal", detail: "Visit scholarships.gov.in and create an account using your Aadhaar and email ID." },
      { title: "Upload Documents", detail: "Upload marksheet (12th), Aadhaar card, ex-serviceman certificate, institution admission proof, bank account details." },
      { title: "Institute Verification", detail: "Your institution principal must verify and approve your application online within the deadline." },
      { title: "Receive Scholarship", detail: "Amount is transferred directly to your bank account via DBT after district-level approval. Two installments per year." }
    ],
    documents: ["Aadhaar Card","12th Marksheet (60%+)","Ex-serviceman Certificate","Admission Letter","Bank Passbook / Account Details","Caste Certificate (if applicable)"]
  },
  {
    id: 2,
    name: "National Scholarship Portal (NSP)",
    name_hi: "राष्ट्रीय छात्रवृत्ति पोर्टल",
    ministry: "Ministry of Electronics & IT",
    icon: "📚",
    icon_bg: "blue",
    description: "Single national platform hosting 50+ scholarship schemes from 10+ ministries. Covers pre-matric, post-matric, and merit-cum-means scholarships for SC/ST/OBC/EWS/Minority students at all levels.",
    description_hi: "50+ छात्रवृत्ति योजनाओं के लिए एकल राष्ट्रीय पोर्टल। SC/ST/OBC/EWS/अल्पसंख्यक छात्रों के लिए।",
    benefit: "Up to ₹50,000 per year (varies by scheme)",
    benefit_hi: "₹50,000 प्रति वर्ष तक (योजना अनुसार)",
    category: "education",
    minAge: 5, maxAge: 30, maxIncome: 1,
    categories: ["obc","sc","st","ews"],
    genders: ["male","female","other"],
    situations: ["student"],
    tags: ["Education","SC/ST/OBC","₹50K/yr","Central"],
    apply_url: "https://scholarships.gov.in",
    official_url: "https://scholarships.gov.in",
    badge: "Popular",
    steps: [
      { title: "Visit Portal", detail: "Go to scholarships.gov.in and click 'New Registration'. Use your Aadhaar card for registration." },
      { title: "Choose Your Scholarship", detail: "Browse available scholarships by your state, religion, category, and level of education (pre/post-matric)." },
      { title: "Fill Application", detail: "Enter personal details, academic information, bank details, and income information as per your income certificate." },
      { title: "Upload Documents", detail: "Upload Aadhaar, marksheet/bonafide certificate, caste/income certificate, bank passbook, and photo." },
      { title: "Institute Verification", detail: "Submit to your institution for principal verification within the due date. Late submissions are rejected." },
      { title: "Receive Scholarship", detail: "After state-level verification, amount is directly credited to your Aadhaar-linked bank account." }
    ],
    documents: ["Aadhaar Card","Marksheet (previous year)","Caste Certificate","Income Certificate","Bank Passbook","School/College Bonafide","Domicile Certificate"]
  },
  {
    id: 3,
    name: "PM Kisan Samman Nidhi",
    name_hi: "पीएम किसान सम्मान निधि",
    ministry: "Ministry of Agriculture & Farmers Welfare",
    icon: "🌾",
    icon_bg: "green",
    description: "Direct income support to all land-holding farmer families across India. Three equal installments of ₹2,000 each, transferred every 4 months directly to the farmer's bank account via DBT.",
    description_hi: "सभी भूमि-धारक किसान परिवारों को प्रत्यक्ष आय सहायता। ₹2,000 की 3 किस्तें, हर 4 महीने में सीधे बैंक खाते में।",
    benefit: "₹6,000 per year (₹2,000 × 3 installments)",
    benefit_hi: "₹6,000 प्रति वर्ष (₹2,000 × 3 किस्तें)",
    category: "agriculture",
    minAge: 18, maxAge: 70, maxIncome: 5,
    categories: ["general","obc","sc","st","ews"],
    genders: ["male","female","other"],
    situations: ["farmer"],
    tags: ["Agriculture","Farmer","₹6K/yr","All India"],
    apply_url: "https://pmkisan.gov.in",
    official_url: "https://pmkisan.gov.in",
    badge: "Popular",
    steps: [
      { title: "Check Land Records", detail: "Verify you own agricultural land in your name. Institutional landholders, income taxpayers, and govt employees are not eligible." },
      { title: "Apply Online or at CSC", detail: "Visit pmkisan.gov.in or your nearest Common Service Centre (CSC/Jan Seva Kendra) with documents." },
      { title: "Submit Documents", detail: "Provide Aadhaar card, land ownership records (Khatauni/Khasra), bank account details, and mobile number." },
      { title: "State Verification", detail: "State Agriculture Department verifies your land records. This process takes 2–4 weeks." },
      { title: "Receive Installments", detail: "After approval, ₹2,000 is credited every 4 months (April, August, December) directly to your bank account." }
    ],
    documents: ["Aadhaar Card","Land Records (Khatauni/Khasra)","Bank Passbook/Account Details","Mobile Number linked to Aadhaar","Ration Card (optional)"]
  },
  {
    id: 4,
    name: "Kisan Credit Card (KCC)",
    name_hi: "किसान क्रेडिट कार्ड",
    ministry: "Ministry of Agriculture & Farmers Welfare",
    icon: "💳",
    icon_bg: "green",
    description: "Flexible revolving credit facility for farmers to meet agricultural input needs, post-harvest expenses, and allied activities. Loan at just 4% effective interest after interest subvention.",
    description_hi: "किसानों के लिए लचीली ऋण सुविधा। कृषि इनपुट, फसल कटाई के बाद के खर्च के लिए। ब्याज सहायता के बाद प्रभावी 4% ब्याज।",
    benefit: "Credit limit up to ₹3 Lakh @ 4% effective interest",
    benefit_hi: "₹3 लाख तक ऋण @ 4% प्रभावी ब्याज",
    category: "agriculture",
    minAge: 18, maxAge: 70, maxIncome: 5,
    categories: ["general","obc","sc","st","ews"],
    genders: ["male","female","other"],
    situations: ["farmer"],
    tags: ["Agriculture","Credit","Loan","4% Interest"],
    apply_url: "https://agricoop.nic.in",
    official_url: "https://agricoop.nic.in",
    badge: null,
    steps: [
      { title: "Visit Bank", detail: "Go to your nearest SBI, cooperative bank, regional rural bank, or any scheduled commercial bank branch." },
      { title: "Fill KCC Form", detail: "Provide details about your crop area, type of crops grown, expected production, and storage facility." },
      { title: "Submit Documents", detail: "Submit land records, Aadhaar card, passport photo, and latest crop details." },
      { title: "Bank Assessment", detail: "Bank officer assesses land records and crop value. Credit limit is set as per land holding and crop cycle." },
      { title: "Card Issued", detail: "KCC (debit card format) is issued within 2 weeks. You can withdraw in multiple tranches as needed." }
    ],
    documents: ["Land Records / Khatauni","Aadhaar Card","Passport Photo","2 References from village","Bank Account Details","Crop Insurance Details (optional)"]
  },
  {
    id: 5,
    name: "PM Awas Yojana (PMAY-Urban)",
    name_hi: "प्रधानमंत्री आवास योजना (शहरी)",
    ministry: "Ministry of Housing & Urban Affairs",
    icon: "🏠",
    icon_bg: "orange",
    description: "Credit-linked subsidy scheme for EWS/LIG/MIG categories to buy or construct their first home. Interest subsidy of ₹1.5L to ₹2.67L on home loan, depending on income group.",
    description_hi: "EWS/LIG/MIG के लिए पहले घर के लिए होम लोन पर ब्याज सब्सिडी। ₹1.5 लाख से ₹2.67 लाख तक।",
    benefit: "Interest subsidy ₹1.5L – ₹2.67L on home loan",
    benefit_hi: "होम लोन पर ₹1.5 लाख – ₹2.67 लाख ब्याज सब्सिडी",
    category: "housing",
    minAge: 18, maxAge: 60, maxIncome: 2,
    categories: ["general","obc","sc","st","ews"],
    genders: ["male","female","other"],
    situations: ["bpl","rural"],
    tags: ["Housing","Subsidy","Home Loan","EWS/LIG"],
    apply_url: "https://pmaymis.gov.in",
    official_url: "https://pmaymis.gov.in",
    badge: null,
    steps: [
      { title: "Check Eligibility", detail: "You must not own a pucca (permanent) house anywhere in India. The property must be in your name or co-applicant's name." },
      { title: "Apply Online or at CSC", detail: "Visit pmaymis.gov.in or nearest Common Service Centre. Fill the application with family details." },
      { title: "Enter Details", detail: "Submit Aadhaar, income certificate, property details, and home loan application with bank of your choice." },
      { title: "Bank Processing", detail: "Bank processes your home loan application. Central Nodal Agency (NHA/HUDCO) verifies eligibility." },
      { title: "Subsidy Credit", detail: "Interest subsidy is credited upfront to your loan account, reducing your EMI substantially." }
    ],
    documents: ["Aadhaar Card","Income Certificate","Address Proof","Property Documents / Land Records","Bank Loan Application","Affidavit (no pucca house)","Caste Certificate (SC/ST/OBC)"]
  },
  {
    id: 6,
    name: "PM Matru Vandana Yojana (PMMVY)",
    name_hi: "प्रधानमंत्री मातृ वंदना योजना",
    ministry: "Ministry of Women & Child Development",
    icon: "🤱",
    icon_bg: "orange",
    description: "Maternity benefit scheme for pregnant and lactating women. Cash incentive for the first living child in 3 installments, linked to antenatal care and vaccination, to compensate wage loss.",
    description_hi: "गर्भवती और स्तनपान कराने वाली महिलाओं के लिए मातृत्व लाभ योजना। पहले जीवित बच्चे के लिए 3 किस्तों में नकद प्रोत्साहन।",
    benefit: "₹5,000 in 3 installments (1st living child)",
    benefit_hi: "₹5,000 तीन किस्तों में (पहले जीवित बच्चे के लिए)",
    category: "women",
    minAge: 19, maxAge: 45, maxIncome: 5,
    categories: ["general","obc","sc","st","ews"],
    genders: ["female"],
    situations: ["pregnant"],
    tags: ["Women","Maternity","₹5,000","Pregnancy"],
    apply_url: "https://pmmvy.wcd.gov.in",
    official_url: "https://pmmvy.wcd.gov.in",
    badge: null,
    steps: [
      { title: "Register Early", detail: "Register at your nearest Anganwadi Centre within 150 days of conception. Carry MCP (Mother & Child Protection) card and Aadhaar." },
      { title: "First Installment (₹1,000)", detail: "Fill Form 1A at Anganwadi. ₹1,000 credited after registration of pregnancy within 150 days of LMP." },
      { title: "Second Installment (₹2,000)", detail: "Fill Form 1B after at least 1 antenatal check-up (ANC). ₹2,000 credited after 6 months of pregnancy." },
      { title: "Third Installment (₹2,000)", detail: "Fill Form 1C after child birth registration and first cycle of immunization (BCG, OPV, DPT, Hepatitis-B)." },
      { title: "DBT Transfer", detail: "All installments are transferred directly to your Aadhaar-linked bank account within 30–60 days." }
    ],
    documents: ["Aadhaar Card (Mother)","Aadhaar Card (Husband)","MCP Card (Mother & Child Protection)","Bank Passbook","Mobile Number","Birth Registration Proof (for 3rd installment)"]
  },
  {
    id: 7,
    name: "Beti Bachao Beti Padhao",
    name_hi: "बेटी बचाओ बेटी पढ़ाओ",
    ministry: "Ministry of Women & Child Development",
    icon: "👧",
    icon_bg: "orange",
    description: "Addresses declining child sex ratio and empowers girl children through education support. Includes Sukanya Samriddhi Yojana for long-term savings, school enrollment drives, and awareness campaigns.",
    description_hi: "बालिका लिंगानुपात सुधार और शिक्षा सशक्तिकरण। सुकन्या समृद्धि खाता, स्कूल नामांकन और जागरूकता अभियान।",
    benefit: "Sukanya Samriddhi savings + education support",
    benefit_hi: "सुकन्या समृद्धि बचत + शिक्षा सहायता",
    category: "women",
    minAge: 0, maxAge: 18, maxIncome: 5,
    categories: ["general","obc","sc","st","ews"],
    genders: ["female"],
    situations: [],
    tags: ["Women","Girl Child","Education","Savings"],
    apply_url: "https://wcd.nic.in/bbbp-schemes",
    official_url: "https://wcd.nic.in",
    badge: null,
    steps: [
      { title: "Contact District Office", detail: "Contact District Women & Child Development office or your nearest Anganwadi Centre." },
      { title: "Register Girl Child", detail: "Register your girl child with AWC/ASHA worker. Ensure birth registration is done." },
      { title: "Ensure School Enrollment", detail: "Enroll daughter in nearest government school. Midday meal and free books/uniform benefits available." },
      { title: "Open Sukanya Samriddhi Account", detail: "Visit nearest Post Office or authorized bank. Account can be opened for girls aged 0–10 years by parent/guardian." },
      { title: "Avail State Benefits", detail: "Many states have additional benefits — cash incentives, scholarships, scholarships for higher education. Check state portal." }
    ],
    documents: ["Girl Child Birth Certificate","Parents Aadhaar","Address Proof","School Enrollment Certificate","Bank Account (for SSY)"]
  },
  {
    id: 8,
    name: "PM MUDRA Yojana",
    name_hi: "प्रधानमंत्री मुद्रा योजना",
    ministry: "Ministry of Finance · MUDRA Ltd.",
    icon: "🏢",
    icon_bg: "blue",
    description: "Collateral-free micro loans for non-farm income generating activities. Three categories: Shishu (up to ₹50K), Kishore (₹50K–₹5L), Tarun (₹5L–₹10L). Loans via banks, NBFCs, MFIs.",
    description_hi: "गैर-कृषि आय सृजन गतिविधियों के लिए बिना जमानत के माइक्रो लोन। शिशु, किशोर, तरुण तीन श्रेणियां।",
    benefit: "Shishu ₹50K | Kishore ₹5L | Tarun ₹10L (no collateral)",
    benefit_hi: "शिशु ₹50K | किशोर ₹5L | तरुण ₹10L (बिना जमानत)",
    category: "business",
    minAge: 18, maxAge: 60, maxIncome: 5,
    categories: ["general","obc","sc","st","ews"],
    genders: ["male","female","other"],
    situations: ["self-employed","unemployed"],
    tags: ["Business","Loan","No Collateral","Startup"],
    apply_url: "https://www.mudra.org.in",
    official_url: "https://www.mudra.org.in",
    badge: "Popular",
    steps: [
      { title: "Choose Loan Category", detail: "Shishu for new/small businesses (up to ₹50K), Kishore for established (₹50K–₹5L), Tarun for expansion (₹5L–₹10L)." },
      { title: "Prepare Business Plan", detail: "Write a simple 1–2 page business plan: what you do, how much you earn, how you'll repay the loan." },
      { title: "Visit Lender", detail: "Approach any PSB (SBI/PNB/BOB), cooperative bank, RRB, MFI, or NBFC. Also apply online via mudra.org.in." },
      { title: "Submit Documents", detail: "Submit Aadhaar, PAN, business proof, address proof, last 6 months bank statement, and business plan." },
      { title: "Get Mudra Card", detail: "Loan is sanctioned within 7–15 working days. You receive a Mudra debit card linked to loan account for easy drawdowns." }
    ],
    documents: ["Aadhaar Card","PAN Card","2 Passport Photos","Business Address Proof","Last 6 Months Bank Statement","Business Registration (if any)","SC/ST Certificate (for priority processing)"]
  },
  {
    id: 9,
    name: "PM Vishwakarma Yojana",
    name_hi: "पीएम विश्वकर्मा योजना",
    ministry: "Ministry of MSME",
    icon: "🔨",
    icon_bg: "orange",
    description: "Holistic support for traditional artisans and craftsmen across 18 trades: carpenter, blacksmith, potter, tailor, goldsmith, cobbler, barber, mason, weaver, and more. Free training, toolkit voucher, and low-interest loan.",
    description_hi: "18 पारंपरिक व्यवसायों के कारीगरों के लिए समग्र सहायता। निःशुल्क प्रशिक्षण, टूलकिट वाउचर और कम ब्याज ऋण।",
    benefit: "₹15,000 toolkit + ₹3 Lakh loan @ 5% interest",
    benefit_hi: "₹15,000 टूलकिट + ₹3 लाख ऋण @ 5% ब्याज",
    category: "employment",
    minAge: 18, maxAge: 60, maxIncome: 2,
    categories: ["general","obc","sc","st","ews"],
    genders: ["male","female","other"],
    situations: ["artisan","self-employed"],
    tags: ["Artisan","Skill","Loan","NEW","Craftsman"],
    apply_url: "https://pmvishwakarma.gov.in",
    official_url: "https://pmvishwakarma.gov.in",
    badge: "NEW",
    steps: [
      { title: "Register on Portal", detail: "Visit pmvishwakarma.gov.in or CSC. Register using Aadhaar-based OTP authentication." },
      { title: "Select Your Trade", detail: "Choose from 18 eligible trades: carpenter, blacksmith, boat maker, armorer, locksmith, hammer & tool kit maker, potter, sculptor, cobbler, mason, basket/mat/broom weaver, doll & toy maker, barber, garland maker, washerman, tailor, fishing net maker, goldsmith." },
      { title: "Attend Training", detail: "Complete 5-day basic training at nearest ITI/skill centre. Then 15-day advanced training. Receive ₹500/day stipend during training." },
      { title: "Get Toolkit Voucher", detail: "After basic training, receive ₹15,000 e-voucher (PM Vishwakarma certificate) to purchase tools from empanelled suppliers." },
      { title: "Apply for Loan", detail: "Phase 1: ₹1 Lakh loan at 5% interest. After repayment and good record: Phase 2: additional ₹2 Lakh at 5%." }
    ],
    documents: ["Aadhaar Card","Mobile linked to Aadhaar","Caste Certificate (if applicable)","Bank Account Details","Artisan/Craft Work Proof (photos acceptable)"]
  },
  {
    id: 10,
    name: "Ayushman Bharat PM-JAY",
    name_hi: "आयुष्मान भारत पीएम-जेएवाई",
    ministry: "Ministry of Health & Family Welfare",
    icon: "🏥",
    icon_bg: "green",
    description: "World's largest government-funded health insurance. Covers hospitalization for 1,500+ medical procedures at 27,000+ empanelled hospitals nationwide. No premium, completely cashless treatment.",
    description_hi: "विश्व की सबसे बड़ी सरकारी स्वास्थ्य बीमा योजना। 27,000+ सूचीबद्ध अस्पतालों में 1,500+ चिकित्सा प्रक्रियाओं के लिए कवरेज।",
    benefit: "₹5 Lakh/year cashless health insurance (per family)",
    benefit_hi: "₹5 लाख प्रति वर्ष कैशलेस स्वास्थ्य बीमा (प्रति परिवार)",
    category: "health",
    minAge: 0, maxAge: 120, maxIncome: 1,
    categories: ["general","obc","sc","st","ews"],
    genders: ["male","female","other"],
    situations: ["bpl","disabled"],
    tags: ["Health","Insurance","BPL","₹5L/yr"],
    apply_url: "https://pmjay.gov.in",
    official_url: "https://pmjay.gov.in",
    badge: "Popular",
    steps: [
      { title: "Check Eligibility", detail: "Visit pmjay.gov.in or call 14555 (toll-free). Enter your Aadhaar or ration card number to check if your family is listed." },
      { title: "Visit CSC or Hospital", detail: "Go to nearest Common Service Centre, government hospital, or any PM-JAY empanelled hospital." },
      { title: "Get Ayushman Card", detail: "Provide Aadhaar and your eligibility details. The Ayushman Bharat card is generated free of cost on the spot." },
      { title: "Use at Hospital", detail: "Show your Ayushman card at any empanelled hospital (government or private). No deposit or pre-payment required." },
      { title: "Cashless Treatment", detail: "Hospital directly claims reimbursement from PM-JAY. You pay absolutely nothing for covered procedures up to ₹5 Lakh." }
    ],
    documents: ["Aadhaar Card","Ration Card (if Aadhaar not linked)","Family Composition Details","Mobile Number"]
  },
  {
    id: 11,
    name: "PM Jeevan Jyoti Bima (PMJJBY)",
    name_hi: "प्रधानमंत्री जीवन ज्योति बीमा योजना",
    ministry: "Ministry of Finance",
    icon: "❤️",
    icon_bg: "blue",
    description: "Renewable 1-year life insurance scheme accessible through banking channel. Extremely low premium covers natural and accidental death, with nominee receiving ₹2 Lakh on death.",
    description_hi: "बैंक चैनल के माध्यम से सुलभ 1 वर्षीय नवीकरणीय जीवन बीमा। केवल ₹436/वर्ष में ₹2 लाख का जीवन कवर।",
    benefit: "₹2 Lakh life cover @ only ₹436/year premium",
    benefit_hi: "₹2 लाख जीवन कवर @ केवल ₹436/वर्ष प्रीमियम",
    category: "social",
    minAge: 18, maxAge: 50, maxIncome: 5,
    categories: ["general","obc","sc","st","ews"],
    genders: ["male","female","other"],
    situations: [],
    tags: ["Insurance","Life Cover","₹436/yr","Bank"],
    apply_url: "https://www.jansuraksha.gov.in",
    official_url: "https://www.jansuraksha.gov.in",
    badge: null,
    steps: [
      { title: "Visit Your Bank", detail: "Go to your bank branch or login to net banking/mobile banking. You need an Aadhaar-linked savings account." },
      { title: "Fill Consent Form", detail: "Fill the PMJJBY enrollment form and give auto-debit consent for ₹436/year from your savings account." },
      { title: "Annual Renewal", detail: "₹436 is auto-debited from your account every year on May 31. Coverage is from June 1 to May 31 next year." },
      { title: "Keep Nominee Updated", detail: "Ensure your nominee details (name, relation, bank account) are correctly registered with your bank." },
      { title: "Making a Claim", detail: "In case of death, nominee submits death certificate, claim form, and bank account details to the bank. Claim settled in 30 days." }
    ],
    documents: ["Aadhaar-linked Bank Account","Aadhaar Card","Nominee Details","Consent Form (available at bank)"]
  },
  {
    id: 12,
    name: "PM Suraksha Bima (PMSBY)",
    name_hi: "प्रधानमंत्री सुरक्षा बीमा योजना",
    ministry: "Ministry of Finance",
    icon: "🛡️",
    icon_bg: "green",
    description: "Renewable 1-year accident insurance for accidental death and disability. At just ₹20/year, it provides ₹2 Lakh for accidental death or full disability, ₹1 Lakh for partial disability.",
    description_hi: "आकस्मिक मृत्यु और विकलांगता के लिए 1 वर्षीय दुर्घटना बीमा। केवल ₹20/वर्ष में ₹2 लाख कवर।",
    benefit: "₹2 Lakh accident cover @ only ₹20/year",
    benefit_hi: "₹2 लाख दुर्घटना कवर @ केवल ₹20/वर्ष",
    category: "social",
    minAge: 18, maxAge: 70, maxIncome: 5,
    categories: ["general","obc","sc","st","ews"],
    genders: ["male","female","other"],
    situations: [],
    tags: ["Insurance","Accident","₹20/yr","Bank"],
    apply_url: "https://www.jansuraksha.gov.in",
    official_url: "https://www.jansuraksha.gov.in",
    badge: null,
    steps: [
      { title: "Visit Bank or Apply Online", detail: "Visit your bank branch or apply via net banking / mobile banking app. Must have an active savings account." },
      { title: "Give Auto-Debit Consent", detail: "Fill PMSBY form with auto-debit consent for ₹20/year from your savings account on June 1 each year." },
      { title: "Coverage Active", detail: "Coverage starts from June 1. Keep your bank account active and ensure minimum balance for auto-debit." },
      { title: "In Case of Accident", detail: "Lodge FIR immediately after accident. Submit disability certificate from CMO or death certificate within 30 days." },
      { title: "Claim Settlement", detail: "Bank submits claim to insurance company. ₹2L for death/full disability (loss of 2 limbs/eyes), ₹1L for partial disability." }
    ],
    documents: ["Aadhaar-linked Bank Account","Aadhaar Card","Nomination Form","Consent Form"]
  },
  {
    id: 13,
    name: "PM Kaushal Vikas Yojana (PMKVY)",
    name_hi: "प्रधानमंत्री कौशल विकास योजना",
    ministry: "Ministry of Skill Development & Entrepreneurship",
    icon: "🛠️",
    icon_bg: "blue",
    description: "Free skill development training program covering 300+ trades and sector-specific courses. Includes Prior Learning Assessment for existing skills, stipend, NSQF-aligned certificate, and job placement support.",
    description_hi: "300+ व्यवसायों में निःशुल्क कौशल विकास प्रशिक्षण। NSQF प्रमाणपत्र, वजीफा और रोजगार सहायता।",
    benefit: "Free training + ₹500 reward + NSQF Certificate",
    benefit_hi: "निःशुल्क प्रशिक्षण + ₹500 पुरस्कार + NSQF प्रमाणपत्र",
    category: "employment",
    minAge: 15, maxAge: 35, maxIncome: 5,
    categories: ["general","obc","sc","st","ews"],
    genders: ["male","female","other"],
    situations: ["unemployed","student"],
    tags: ["Skill","Training","Employment","Free","Youth"],
    apply_url: "https://www.pmkvyofficial.org",
    official_url: "https://www.pmkvyofficial.org",
    badge: "Popular",
    steps: [
      { title: "Find Training Centre", detail: "Visit pmkvyofficial.org or skillindiadigital.gov.in. Find nearest empanelled training centre by state/district/trade." },
      { title: "Register Online", detail: "Register with Aadhaar, mobile number, and educational qualification. Choose your preferred trade/sector." },
      { title: "Attend Free Training", detail: "Training duration varies from 2 weeks to 3 months based on trade. Attendance is mandatory (minimum 80%)." },
      { title: "Assessment & Certification", detail: "Sector Skill Council (SSC) conducts assessment exam. Passing score = NSQF-aligned certificate issued." },
      { title: "Certificate & Reward", detail: "Receive NSQF certificate + ₹500 reward on successful completion. Job placement support provided by training centre." }
    ],
    documents: ["Aadhaar Card","Educational Certificate (minimum 8th pass for most trades)","Mobile Number","2 Passport Photos","Bank Account Details"]
  },
  {
    id: 14,
    name: "Indira Gandhi Old Age Pension (IGNOAPS)",
    name_hi: "इंदिरा गांधी राष्ट्रीय वृद्धावस्था पेंशन",
    ministry: "Ministry of Rural Development · NSAP",
    icon: "👴",
    icon_bg: "orange",
    description: "Monthly pension for BPL senior citizens aged 60 and above. ₹200/month for 60–79 years and ₹500/month for 80+ years. Most states provide additional top-up, making effective pension much higher.",
    description_hi: "60 वर्ष और उससे अधिक आयु के BPL वरिष्ठ नागरिकों के लिए मासिक पेंशन। ₹200–₹500/माह + राज्य सरकार का अतिरिक्त लाभ।",
    benefit: "₹200–₹500/month + state government top-up",
    benefit_hi: "₹200–₹500/माह + राज्य सरकार का अतिरिक्त अंशदान",
    category: "social",
    minAge: 60, maxAge: 120, maxIncome: 0,
    categories: ["general","obc","sc","st","ews"],
    genders: ["male","female","other"],
    situations: ["senior","bpl"],
    tags: ["Senior Citizen","Pension","BPL","60+"],
    apply_url: "https://nsap.nic.in",
    official_url: "https://nsap.nic.in",
    badge: null,
    steps: [
      { title: "Visit Local Office", detail: "Rural: Visit your Gram Panchayat office. Urban: Visit Ward Office or Municipal Corporation." },
      { title: "Get Application Form", detail: "Obtain IGNOAPS application form from Gram Panchayat/Ward office or download from nsap.nic.in." },
      { title: "Fill and Submit", detail: "Fill form with personal details, bank details, and attach required documents. Submit to Gram Pradhan or Ward Councillor." },
      { title: "Verification Process", detail: "Block Development Officer / District Social Welfare Officer verifies BPL status and age. Takes 30–60 days." },
      { title: "Monthly Pension", detail: "After approval, monthly pension is transferred directly to your bank/post office account." }
    ],
    documents: ["Aadhaar Card","Age Proof (Birth Certificate/School Certificate/Voter ID)","BPL Card / Ration Card","Bank Passbook","Residence Proof","2 Passport Photos"]
  },
  {
    id: 15,
    name: "NHFDC Loan for Disabled Persons",
    name_hi: "NHFDC दिव्यांग व्यक्तियों के लिए ऋण",
    ministry: "Ministry of Social Justice & Empowerment",
    icon: "♿",
    icon_bg: "blue",
    description: "National Handicapped Finance & Development Corporation provides low-interest loans to persons with disabilities for education, self-employment, and business ventures through State Channelising Agencies.",
    description_hi: "दिव्यांग व्यक्तियों के लिए शिक्षा, स्वरोजगार और व्यावसायिक उद्यमों के लिए कम ब्याज पर ऋण।",
    benefit: "Loan up to ₹50 Lakh @ 5% interest rate",
    benefit_hi: "₹50 लाख तक ऋण @ 5% ब्याज दर",
    category: "social",
    minAge: 18, maxAge: 55, maxIncome: 2,
    categories: ["general","obc","sc","st","ews"],
    genders: ["male","female","other"],
    situations: ["disabled"],
    tags: ["Disabled","Loan","5% Interest","Self-Employment"],
    apply_url: "https://nhfdc.nic.in",
    official_url: "https://nhfdc.nic.in",
    badge: null,
    steps: [
      { title: "Get Disability Certificate", detail: "Obtain Disability Certificate from Chief Medical Officer (CMO) or authorized Medical Board. Minimum 40% disability required." },
      { title: "Contact State Agency", detail: "Contact your State Channelising Agency (SCA) — state corporation for persons with disabilities or NSDC." },
      { title: "Submit Application", detail: "Submit disability certificate, business plan, Aadhaar, address proof, income proof, and bank statements to SCA." },
      { title: "SCA Verification", detail: "SCA visits your location, verifies disability, assesses business viability, and forwards recommendation to NHFDC." },
      { title: "Loan Disbursement", detail: "NHFDC sanctions and loans are disbursed through SCA in installments as per business requirement." }
    ],
    documents: ["Disability Certificate (40%+ from CMO)","Aadhaar Card","Address Proof","Business Plan","Bank Statement (last 6 months)","Income Proof","Photographs"]
  },
  {
    id: 16,
    name: "Stand Up India",
    name_hi: "स्टैंड अप इंडिया",
    ministry: "Ministry of Finance · SIDBI",
    icon: "💡",
    icon_bg: "orange",
    description: "Loan facility for SC/ST and women entrepreneurs to set up a greenfield enterprise. At least 1 SC/ST borrower and 1 woman borrower per bank branch. For manufacturing, services, or trading sectors.",
    description_hi: "SC/ST और महिला उद्यमियों के लिए नई ग्रीनफील्ड उद्यम स्थापित करने के लिए ऋण सुविधा।",
    benefit: "Loan ₹10 Lakh to ₹1 Crore for greenfield enterprise",
    benefit_hi: "ग्रीनफील्ड उद्यम के लिए ₹10 लाख से ₹1 करोड़ ऋण",
    category: "business",
    minAge: 18, maxAge: 60, maxIncome: 5,
    categories: ["sc","st"],
    genders: ["male","female","other"],
    situations: ["self-employed","unemployed"],
    tags: ["Business","SC/ST","Women","Startup","₹1Cr"],
    apply_url: "https://www.standupmitra.in",
    official_url: "https://www.standupmitra.in",
    badge: null,
    steps: [
      { title: "Register on Portal", detail: "Visit standupmitra.in. Register with Aadhaar, PAN, and basic business details." },
      { title: "Select Bank Branch", detail: "Choose the nearest scheduled commercial bank branch where you want to apply for the loan." },
      { title: "Prepare Business Plan", detail: "Prepare a detailed business plan for a NEW (greenfield) enterprise in manufacturing, services, or trading." },
      { title: "Apply at Bank", detail: "Submit online application or visit the selected branch with all documents. Bank has 90 days to sanction or reject." },
      { title: "Loan Sanctioned", detail: "Bank sanctions loan (usually within 8 weeks). Collateral not mandatory up to ₹10L. Credit guarantee cover available." }
    ],
    documents: ["Aadhaar Card","PAN Card","SC/ST or Women Entrepreneur Certificate","Business Plan","Address Proof (Business & Personal)","Bank Statements","Project Report"]
  },
  {
    id: 17,
    name: "Sukanya Samriddhi Yojana",
    name_hi: "सुकन्या समृद्धि योजना",
    ministry: "Ministry of Finance · India Post",
    icon: "👧",
    icon_bg: "orange",
    description: "Government-backed high-interest savings scheme for girl child education and marriage. Opened by parent/guardian for girl aged 0–10 years. Matures at girl's age 21, partial withdrawal at 18.",
    description_hi: "बालिकाओं की शिक्षा और विवाह के लिए सरकारी उच्च-ब्याज बचत योजना। 0–10 वर्ष की बालिका के लिए खाता खोलें।",
    benefit: "8.2% interest p.a. | Tax-free | Matures at age 21",
    benefit_hi: "8.2% ब्याज | कर-मुक्त | 21 वर्ष में परिपक्वता",
    category: "women",
    minAge: 0, maxAge: 10, maxIncome: 5,
    categories: ["general","obc","sc","st","ews"],
    genders: ["female"],
    situations: [],
    tags: ["Girl Child","Savings","8.2%","Tax-Free"],
    apply_url: "https://www.indiapost.gov.in",
    official_url: "https://www.indiapost.gov.in",
    badge: null,
    steps: [
      { title: "Visit Post Office or Bank", detail: "Visit nearest Post Office (India Post) or any authorized bank (SBI, PNB, Axis, HDFC, etc.) that offers SSY." },
      { title: "Fill Account Opening Form", detail: "Fill SSY account opening form with girl child and parent/guardian details." },
      { title: "Deposit Minimum Amount", detail: "Minimum ₹250 to open. Maximum ₹1.5 Lakh per year. Account must be kept active with minimum ₹250/year." },
      { title: "Deposit Regularly", detail: "Deposits can be made monthly or annually. Deposits allowed for 15 years from account opening date." },
      { title: "Maturity & Withdrawal", detail: "50% withdrawal allowed at girl's age 18 (for education/marriage). Full maturity at age 21 — withdrawable by the girl." }
    ],
    documents: ["Girl Child Birth Certificate","Parent/Guardian Aadhaar","Parent/Guardian Address Proof","Photographs","Initial Deposit (minimum ₹250)"]
  },
  {
    id: 18,
    name: "PM Ujjwala Yojana",
    name_hi: "प्रधानमंत्री उज्ज्वला योजना",
    ministry: "Ministry of Petroleum & Natural Gas",
    icon: "🍳",
    icon_bg: "green",
    description: "Free LPG connections to BPL households (below poverty line) to provide clean cooking fuel. Protects women and children from indoor air pollution from traditional biomass-based cooking fuels.",
    description_hi: "BPL परिवारों को निःशुल्क एलपीजी कनेक्शन। महिलाओं और बच्चों को पारंपरिक ईंधन के धुएं से बचाव।",
    benefit: "Free LPG connection + ₹1,600 financial support",
    benefit_hi: "निःशुल्क एलपीजी कनेक्शन + ₹1,600 वित्तीय सहायता",
    category: "women",
    minAge: 18, maxAge: 120, maxIncome: 1,
    categories: ["general","obc","sc","st","ews"],
    genders: ["female"],
    situations: ["bpl","rural"],
    tags: ["Women","LPG","BPL","Free Connection"],
    apply_url: "https://www.pmuy.gov.in",
    official_url: "https://www.pmuy.gov.in",
    badge: null,
    steps: [
      { title: "Visit LPG Distributor", detail: "Visit nearest HP Gas, Bharat Gas, or Indane distributor outlet in your area." },
      { title: "Fill KYC Form", detail: "Fill the Ujjwala KYC (Know Your Customer) form available at the distributor's office." },
      { title: "Submit Documents", detail: "Submit Aadhaar card, BPL card / Ration card with State BPL list entry, and bank account details." },
      { title: "Distributor Verification", detail: "Distributor verifies BPL status and submits your application to the oil company. Takes 15–30 days." },
      { title: "Connection Delivery", detail: "Free LPG cylinder and stove are delivered to your doorstep. ₹1,600 support for stove + first refill via EMI." }
    ],
    documents: ["Aadhaar Card","BPL Card or Ration Card","Bank Passbook","Mobile Number","Photograph","Address Proof"]
  }
];
