// build.js — runs on Vercel during deployment
// Reads SUPABASE_URL and SUPABASE_ANON_KEY from Vercel env vars
// and writes them into supabase-config.js
// You never need to put API keys in your code or GitHub

const fs = require('fs');

const SUPABASE_URL     = process.env.SUPABASE_URL     || 'YOUR_SUPABASE_URL';
const SUPABASE_ANON_KEY = process.env.SUPABASE_ANON_KEY || 'YOUR_SUPABASE_ANON_KEY';

const content = `// Auto-generated by build.js — do not edit manually
// API keys come from Vercel Environment Variables, not GitHub

const SUPABASE_URL      = '${SUPABASE_URL}';
const SUPABASE_ANON_KEY = '${SUPABASE_ANON_KEY}';

let supabase = null;

try {
  if (SUPABASE_URL !== 'YOUR_SUPABASE_URL') {
    const script = document.createElement('script');
    script.src = 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2';
    script.onload = () => {
      const { createClient } = window.supabase;
      supabase = createClient(SUPABASE_URL, SUPABASE_ANON_KEY);
      console.info('Supabase connected');
    };
    script.onerror = () => {
      console.warn('Supabase SDK failed to load. Using local scheme data.');
    };
    document.head.appendChild(script);
  } else {
    console.info('No Supabase credentials — using local scheme data (schemes-data.js).');
  }
} catch(e) {
  console.warn('Supabase init error:', e.message);
}
`;

fs.writeFileSync('supabase-config.js', content);
console.log('✅ supabase-config.js generated from environment variables');
console.log('   SUPABASE_URL set:', SUPABASE_URL !== 'YOUR_SUPABASE_URL');
console.log('   SUPABASE_ANON_KEY set:', SUPABASE_ANON_KEY !== 'YOUR_SUPABASE_ANON_KEY');
